Tildes y typos arreglados en el post
brabob-b/hyperblog pull request #1
Opened 2022-04-21 05:24 UTC by brabob-b

No debimos pasar este error a master

2022-04-21 05:28 UTC, anami-a requested changes
En vez de usar tildes directas, usa entidades HTML

2022-04-21 05:36 UTC, brabob-b commented
Cambios hechos, por favor hazme el merge

2022-04-21 05:38 UTC, anami-a approved these changes
Excelente. Eso era!

2022-04-21 05:40 UTC, merged

2022-04-22 03:02 UTC, brabob-b commented
con gusto